### PR TITLE
Improvements to macro tutorial

### PR DESCRIPTION
**Pull request by Homo-carbonis**
I've added some more headings and improved the wording.

### CODE REVIEW

**Comment by daninus14** [comment]
Hi, did you pull merge form the original repo before pushing the fork? the reason I'm asking is because it deletes the TODO items in the end of the file

**Comment by Homo-carbonis** [comment]
Hello, I have covered all of them in the tutorial to some extent, with the exception of reader macros. I added some headings to introduce the subjects as they arise.

**Comment by daninus14** [comment]
Great, good job! Thanks for the contribution. Keep it up 😄

**Comment by daninus14** [comment]
It's live now! https://lisp-docs.github.io/docs/macros

**Pull request merged**
